/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RecoverRouteImport } from './routes/recover'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as LoginApproveRouteImport } from './routes/login.approve'
import { Route as LoginPccpRouteImport } from './routes/login.pccp'
import { Route as PccpSetupRouteImport } from './routes/pccp.setup'
import { Route as SettingsSecurityRouteImport } from './routes/settings.security'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverRoute = RecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginApproveRoute = LoginApproveRouteImport.update({
  id: '/login/approve',
  path: '/login/approve',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPccpRoute = LoginPccpRouteImport.update({
  id: '/login/pccp',
  path: '/login/pccp',
  getParentRoute: () => rootRouteImport,
} as any)
const PccpSetupRoute = PccpSetupRouteImport.update({
  id: '/pccp/setup',
  path: '/pccp/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accounts': typeof AccountsRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/recover': typeof RecoverRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/transfer': typeof TransferRoute
  '/verify-email': typeof VerifyEmailRoute
  '/login/approve': typeof LoginApproveRoute
  '/login/pccp': typeof LoginPccpRoute
  '/pccp/setup': typeof PccpSetupRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/login/': typeof LoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accounts': typeof AccountsRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/recover': typeof RecoverRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/transfer': typeof TransferRoute
  '/verify-email': typeof VerifyEmailRoute
  '/login/approve': typeof LoginApproveRoute
  '/login/pccp': typeof LoginPccpRoute
  '/pccp/setup': typeof PccpSetupRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/login': typeof LoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accounts': typeof AccountsRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/recover': typeof RecoverRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/transfer': typeof TransferRoute
  '/verify-email': typeof VerifyEmailRoute
  '/login/approve': typeof LoginApproveRoute
  '/login/pccp': typeof LoginPccpRoute
  '/pccp/setup': typeof PccpSetupRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/login/': typeof LoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accounts'
    | '/activity'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/onboarding'
    | '/privacy'
    | '/recover'
    | '/security'
    | '/signup'
    | '/terms'
    | '/transfer'
    | '/verify-email'
    | '/login/approve'
    | '/login/pccp'
    | '/pccp/setup'
    | '/settings/security'
    | '/login/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accounts'
    | '/activity'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/onboarding'
    | '/privacy'
    | '/recover'
    | '/security'
    | '/signup'
    | '/terms'
    | '/transfer'
    | '/verify-email'
    | '/login/approve'
    | '/login/pccp'
    | '/pccp/setup'
    | '/settings/security'
    | '/login'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accounts'
    | '/activity'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/onboarding'
    | '/privacy'
    | '/recover'
    | '/security'
    | '/signup'
    | '/terms'
    | '/transfer'
    | '/verify-email'
    | '/login/approve'
    | '/login/pccp'
    | '/pccp/setup'
    | '/settings/security'
    | '/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountsRoute: typeof AccountsRoute
  ActivityRoute: typeof ActivityRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  RecoverRoute: typeof RecoverRoute
  SecurityRoute: typeof SecurityRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  TransferRoute: typeof TransferRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  LoginApproveRoute: typeof LoginApproveRoute
  LoginPccpRoute: typeof LoginPccpRoute
  PccpSetupRoute: typeof PccpSetupRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover': {
      id: '/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof RecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/approve': {
      id: '/login/approve'
      path: '/login/approve'
      fullPath: '/login/approve'
      preLoaderRoute: typeof LoginApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/pccp': {
      id: '/login/pccp'
      path: '/login/pccp'
      fullPath: '/login/pccp'
      preLoaderRoute: typeof LoginPccpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pccp/setup': {
      id: '/pccp/setup'
      path: '/pccp/setup'
      fullPath: '/pccp/setup'
      preLoaderRoute: typeof PccpSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountsRoute: AccountsRoute,
  ActivityRoute: ActivityRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  RecoverRoute: RecoverRoute,
  SecurityRoute: SecurityRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  TransferRoute: TransferRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  LoginApproveRoute: LoginApproveRoute,
  LoginPccpRoute: LoginPccpRoute,
  PccpSetupRoute: PccpSetupRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
